# This is the serverless configuration file for the r10kwebhook Lambda. Please
# refer to README.md for further information.
#
# For documentation around the Serverless framework, please see:
# docs.serverless.com


service: r10k-webhook

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7
  stage: staging
  region: us-east-1

  # Grant the Lamba permission to create and push to an SNS topic based on the
  # name + stage of this Lambda. We do some horrible assembly of the name using
  # a mix of CloudFormation variables and Serverless variable.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "SNS:Publish"
      Resource: { "Fn::Join" : ["", ["arn:aws:sns:", { "Ref" : "AWS::Region" }, ":", { "Ref" : "AWS::AccountId" }, ":${self:service}-${self:provider.stage}" ] ]  }

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  webhook:
    handler: handler.webhook
    description: Provides a webhook endpoint that generates SNS messages for r10k consumer.
    memorySize: 128 # MB
    timeout: 10
    events:
      - http:
          path: /
          method: post

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
